In [11]:
import pandas as pd

In [12]:
url = r'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'

df = pd.read_csv(url)
display(df.head())
display(df.tail())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [13]:
# Passando métricas de Análise

display('Valores Duplicados:', df[df.duplicated(keep=False)])
display('Valores nulos:', df.isnull().sum())
display('Linhas x Colunas:', df.shape)
display('Linhas x Colunas:', df.count())
display('Tipos de Dados:', df.dtypes)
display('Estatísticas de dados:', df.describe())

display(f'Antes: {len(df)} valores')

'Valores Duplicados:'

     total_bill  tip     sex smoker   day   time  size
198        13.0  2.0  Female    Yes  Thur  Lunch     2
202        13.0  2.0  Female    Yes  Thur  Lunch     2

'Valores nulos:'

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

'Linhas x Colunas:'

(244, 7)

'Linhas x Colunas:'

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

'Tipos de Dados:'

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

'Estatísticas de dados:'

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

'Antes: 244 valores'

In [14]:
# Pós remoção de duplicata
df = df.drop_duplicates()

df[df.duplicated(keep=False)]
print(f'Após remoção: {len(df)} valores')

Após remoção: 243 valores

In [15]:
# Repassando distribuição

display('Estatísticas de dados:', df.describe())

'Estatísticas de dados:'

       total_bill         tip        size
count  243.000000  243.000000  243.000000
mean    19.813868    3.002387    2.572016
std      8.910071    1.385002    0.952356
min      3.070000    1.000000    1.000000
25%     13.380000    2.000000    2.000000
50%     17.810000    2.920000    2.000000
75%     24.175000    3.575000    3.000000
max     50.810000   10.000000    6.000000